services:
  rediseq:
    container_name: email-queue-redis
    image: redis:8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - email-queue-network
    command: ["redis-server", "--appendonly", "yes"]

  worker:
    build: ./email-worker
    environment:
      - SENDER_EMAIL=yourmail@example.com
      - SMTP_PASS=secret_password
    networks:
      - email-queue-network
    depends_on:
      - rediseq
  backend:
    build: ./backend
    networks:
      - email-queue-network
    ports:
      - 3001:3001
    depends_on:
      - rediseq

volumes:
  redis-data:
networks:
  email-queue-network:
    driver: bridge
